

export const REQUEST_USER = "REQUEST_USER"
export const SET_ERROR_USER = "SET_ERROR_USER"
export const SET_DATA_USER = "SET_DATA_USER"
export const UPDATE_DATA_USER = "UPDATE_DATA_USER"

export const REQUEST_PROJECT = "REQUEST_PROJECT"
export const SET_ERROR_PROJECT = "SET_ERROR_PROJECT"
export const SET_DATA_PROJECT = "SET_DATA_PROJECT"
export const UPDATE_DATA_PROJECT = "UPDATE_DATA_PROJECT"

export const REQUEST_APP = "REQUEST_APP"
export const SET_ERROR_APP = "SET_ERROR_APP"
export const SET_DATA_APP = "SET_DATA_APP"
export const UPDATE_DATA_APP = "UPDATE_DATA_APP"